# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: BUG研发中心
subtitle: 
description: "Warning: inexperienced programmer inside!"
author: Dr. A. Clef
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://unnamed42.github.io
root: /
permalink: :year-:month-:day-:title.html
permalink_defaults:
lang: zh-CN

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

archive_generator: 
  per_page: 0
  yaerly: true
  monthly: true

category_generator:
  per_page: 0

tag_generator:
  per_page: 0

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: kunkka

plugins:
  - hexo-generator-archive
  - hexo-generator-category
  - hexo-generator-feed
  - hexo-generator-index
  - hexo-generator-tag
  - hexo-generator-search
  - hexo-renderer-markdown-it
  - hexo-renderer-ejs
  - hexo-renderer-stylus
  - hexo-deployer-git
  - hexo-uglify
  - hexo-clean-css
  - hexo-html-minifier
  - hexo-front-matter
  - hexo-pagination
  - hexo-fs
  - hexo-log
  - hexo-cli
  - hexo-util
  - hexo-i18n
  - hexo-server
  - hexo-spoiler
  - hexo-wordcount
  - hexo-tag-bilibili
  - hexo-ruby-character


# Feed
feed: 
  type: atom
  path: atom.xml
  limit: 20
  hub: 

# markdown-it
markdown:
  render: 
    html: true
    xhtmlOut: true
    breaks: false
    linkify: true
    typographer: true
  plugins:
    - markdown-it-footnote
  anchors:
    level: 1
    collisionSuffix: 'v'
    permalink: false
    permalinkClass: header-anchor

# Stylus
stylus: 
  compress: false

# jQuery search
search: 
  path: search.xml
  field: post

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/unnamed42/unnamed42.github.io.git
  branch: master

server:
  port: 4000
  log: false
  ip: 0.0.0.0
  compress: false
  header: true

html_minifier:
  minifyCSS: true
  minifyJS: true
  minifyURLs: true
  collapseWhitespace: true
  removeComments: true
  removeAttributeQuotes: true
  removeEmptyAttributes: true
  removeRedundantAttributes: true
  processScripts: 
    - "text/x-mathjax-config"
  useShortDoctype: true
clean_css:
  exclude:
    - "*.min.css"
uglify:
  mangle: true
  output:
  compress:
  exclude:
    - "*.min.js"
